### ISSUE TITLE
Wild Lentil Genomes for BLAST

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#16]
We would like to put the NRGene assemblies up for BLAST (restricted to UofS peoples).

@Jiu9Shen has created the blast databases but I just realized that I forgot about prefixing the assemblies first.

So, updated instructions:
1. I've decided to change the versions from 0.8 to 0.2 since this is actually only the second version we've received from NRGene. Could you make this change in the file names and READMEs?
2. Use https://gist.github.com/laceysanderson/12b1de6784413cd69cbb064666063b08 to prefix each file:
    - Lamottei Genome should be prefixed `Lla0.2_`
    - Odemensis Genome should be prefixed `Lod0.2_`
3. Create the BLAST indices as previously described. Example Command: 
> formatdb -p F -t Colletotrichum_lentis_CT30_genome -i Colletotrichum_lentis_CT30_genome.fasta -n Colletotrichum_lentis_CT30_genome -o T
4. Create BLAST database on KnowPulse. Go to Admin Toolbar > Content > Add Content > Blast Database and enter the information as follows:
   - Lamottei Genome
        - Name: `Lens lamottei: Genome 0.2`
        - Path: [enter the path to the blast database on KnowPulse including the filename without extension for lamottei]
        - Linkouts: None
        - Access: University of Saskatchewan
    - Odemensis: same as lamottei respectively.

**Comment by Jiu9Shen** [comment]
For undated instructions 1, 2 and 3:
After change file name and prefix each file, file for Lamottei Genome (lens_lamottei_genome_prefixed.v0.2.fasta) and file for Odemensis Genome (lens_odemensis_genome_prefixed.v0.2.fasta) are saved in knowpulse dir /home/yis412. 
It seems the README file doesn't contain any version information (0.8 or 0.2), so no change in made. 
The indices files are produced using command "formatdb" along with other files with different extensions:
Extension     content
nhr                deflines
nin                indices
nsd                Non-GI data
nsi                 Non_GI indices
nsq                sequencing data.
All files are saved in knowpulse dir /home/yis412.

For instruction 4:
The BLAST databases for Lamottei and Odemensis have been created. My apologize  for enter a wrong path without asking. The path is still need to be revised.

**Comment by laceysanderson** [comment]
Path has been revised -genomes are now available 👍
