### ISSUE TITLE
Exome Capture on VCF Filter

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#17]
Our L.culinaris Exome Capture (first couple rounds) needs to go up on KnowPulse.

The file has been put with the other VCF filter files.

@Jiu9Shen can you run your stats program on it and add the results here?
@carolyncaron we will need to decide whether this should be filtered further.

**Comment by Jiu9Shen** [comment]
The basic statistic summary has been passed to Carolyn. The result is double checked by another run of the program and the .lmiss, .frq and .gdepth files produced by vcftools are kept in knowpuse dir /home/yis412/vcf_stats_sum for further analysis if necessary.

**Comment by carolyncaron** [comment]
This was put on hold when the decision was made to not distribute the exome capture set before it was fully processed for all samples. Now the set is almost complete, and we are leaning toward not putting it up at all through VCF filter. To be continued...
