### ISSUE TITLE
Stocks part of the AGILE LDP need to be reflected as single-derived plants

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#19]
Currently we are entering genotypic and phenotypic data for AGILE using the generic "seed bank" or variety name for germplasm. We need some way to reflect that a lot of work has been done to ensure single plant derived sources for the seed we're using and distributing as part of AGILE. 

Two suggestions have been made so far:
1. Create individual records for each LDP member, and name them by adding a prefix relevant to AGILE (Crystal recommended against suffixes thanks to USDA's LSPs).

    My concern with this route is people who may choose to download phenotypic data from AGILE and use genotypic data from another source (for example, the UCDavis GBS set). Both of these downloads would result in different names for germplasm, creating quite the headache for the researcher to resolve, especially for GWAS!

2. Have some way to link stocks and phenotypic/genotypic data to a specific DOI or unique identifier for a seed source. The plant community is increasingly calling for DOIs for seed sources, so we can try to incorporate that into KP - but this requires us waiting for the community to implement it.

**Comment by carolyncaron** [comment]
Kirstin has emphasized that this is too urgent to wait - researchers from our group and collaborators will begin to analyze the data very soon.

Points brought up in our recent meeting:
1. Kirstin's biggest worry is that people will interpret the current names as the original seed source for those plants. She wants the name to be different to reflect those differences.
2. Spreadsheets for the remaining phenotypic trials have already been sent out. To avoid the embarrassment of sending them again, Reynold and I agreed we could look into having the system automatically append whatever identifier we settle on for AGILE when data is uploaded to raw phenotypes. Re-sending the spreadsheets may also cause confusion since the seed has also been sent.
3. Crystal, on the other hand, is reluctant to rename the entire panel and is hoping for a solution closer to the DOI proposal. To ensure that collaborators know the source of the data, we need a way to make it clear when they access the phenotypic and genotypic data in KnowPulse. This includes being able to distinguish genotypes in the genotype matrix by project or dataset. Bottom line, when they search for a particular germplasm in KP, will they be able to quickly and easily distinguish the one they are looking for?
    - Though not as urgent, the following project is an example of how important it is that we think carefully about our solution to this problem. A researcher in our group is studying the genotypes and phenotypes of one of our varieties across multiple (many dozens, if I recall correctly) locations in Saskatchewan. We will want to ensure that all of the samples are distinct when entered into the system, but that they all relate back to the original variety. Although this can be done by using different names, how do we go about naming them? Crystal shudders to think of sample_name 1, sample_name 2, etc...
4. Lastly, Larissa is almost done processing the exome capture data.... with the original names. Though I don't think renaming the header in the VCF file will be difficult, updating the LIMS might be another story!
5. Something to keep in mind but not necessarily adding to the problem... Crystal pointed out that our new seed will eventually be sent to other seed banks, who will handle naming it in their own way. What they do is out of our control, but yet another batch of names will be floating around for this panel.  

***Massive Exhale***

**Comment by laceysanderson** [comment]
Done :-) "AGL" Lines are on my main portal

We chose option #1. However, the concern about mismatched names between genotype and phenotype data has been resolved with the availability of the exome capture. Sometimes if you wait long enough your problems are solved ;-)

When the names were changed the following pointers were updated:
 - phenotypic data
 - exome capture
NOTE: LIMS has not, project doesn't yet have a stock collection.

**Comment by laceysanderson** [comment]
## Updating the LIMS
This is a bit more involved then simply query magic since we are not sure which collection of lanes needs to be updated. Thus @carolyncaron will follow up with Kirstin/Crystal/Larissa to determine if all AGILE exome capture lanes should be updated to point to the AGL lines? Perhaps the preliminary exome capture should not as was the case with the phenotypic data?
