### ISSUE TITLE
Duplicated germplasm names for lentil

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/KnowPulse#20]
Two germplasms with duplication are found so far for lentil on Knowpulse: IG 72534 and PI 320953. 

For two 'PI 320953's, two KP accessions are: 'KP:GERM***36' and 'KP:GERM***44'. Each one has some unique information, so it is hard to determine which one need to be deleted or set as duplicate. 

For two 'IG 72534's, two KP accessions are: 'KP:GERM***50' and 'KP:GERM***86'. Based on Kirstin's email about this germplasm, 'KP:GERM***50' has been edited and 'KP:GERM***86' has been set as IG 72534 (duplicate).

**Comment by carolyncaron** [comment]
Email from Kirstin on Dec 19 reads:
> There is a lot of confusion about this line. In Genesys it is listed as tomentosus. In the GBS paper that Melissa did it pops up as odemensis - but on closer inspection it is coming up identical to IG 72543 - an inversion typo!  So it is probably not odemensis. If you look in Genesys at the Russian version of this line they claim it is orientalis. Which is indeed where it falls out with the exome capture data.  Gotta love those gene banks!
So, ... we seem to have 2 entries in KP for this line. One under tomentosus and the other under odemensis. I am not sure which is attached to the exome capture data but that one for sure should probably be changed to orientalis, correct? What do we do with the other???

**Comment by laceysanderson** [comment]
Fixed 👍
