### ISSUE TITLE
Export GFF3 from Apollo

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#27]
Since a couple of collaborators have updated our annotation for lentil through Apollo, I need to set aside some time to export the GFF3. Then, the GFF3 will need to be updated in the following places:
- [x] File download
- [x] Annotations tracks on the lentil JBrowse

**Comment by laceysanderson** [comment]
Where are we on this @Jiu9Shen and @carolyncaron ?

**Comment by carolyncaron** [comment]
We've now had contributions from 4 different sources, so we've made the decision to officially release a single new version of the annotation file for distribution by incorporating all the changes so far into one file. We anticipate there won't be any more changes before the new genome assembly... *fingers crossed*
[ ] Check the full GFF3 with fixed phase information that it complies with JBrowse and no additional changes were introduced - we'll start with this file as our base
[ ] Determine how we want to incorporate user-annotated genes without losing original gene information
[ ] Verify the changes through Apollo by Mohammed, then export and pull out the differences like previous changes
[ ] Somehow merge everything together!
[ ] Name the new file such that it is clearly a new version, then complete the checklist in my first post

**Comment by Jiu9Shen** [comment]
it's better to update script used to merge files to this issue, we may need to repeat this job @Jiu9Shen

**Comment by Jiu9Shen** [comment]
The script of merging two files is available in my local. Decide not to create a git for it since the script is customised for our unique situation and includes info of our annotators.
