### ISSUE TITLE
Script to update locations for new genome

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#32]
We need our own script for updating the location of markers on new Genomes. 

### Motivation
I have all these wonderful markers that my users have published on and now there's a new version of the genome... They want to extract sequence and see context based on this new genome so I need to add their possible locations on it.

### Input
A. FASTA File for old genome
B. GFF3 with current location
C. FASTA file for new genome

### Steps
1. Extract flanking sequence for markers using A and B.
2. Align that flanking sequence on C
3. Filter for "good" alignments
4. Create GFF3 version of the alignments? Maybe as limited as `match_part` => region matched on C
5. Add records to GFF3 for the actual SNP using your knowledge of how you extracted flanking sequence in step 1

### Beware
 - The off by one error is really easy to introduce here!
 - If you extract 500bp flanking sequence, you way not get 500bp flanking sequence b/c the SNP may lie at the beginning/end of a FASTA record
 - A might be a cDNA set  rather then a genome. It may also be a very fragmented genome

**Comment by Jiu9Shen** [comment]
[Perl scripts for this job (Using Bowtie2 for alignment)](https://gist.github.com/Jiu9Shen/d1c06821b355db0d352f89c93cf1ae92)

**Comment by Jiu9Shen** [comment]
Bowtie2 is fast for short sequence alignments (<1000 nt), but not ideal for long sequence alignments.

**Comment by Jiu9Shen** [comment]
Therefore, try GMAP for gene location update

**Comment by laceysanderson** [comment]
Where are we on this @Jiu9Shen? If complete and in GIST form, can you add a link here and close this issue?

**Comment by Jiu9Shen** [comment]
Script for update **marker** locations on new genome is done, and the line is above. @laceysanderson 
Script for update **gene** locations on new genome seems unfinished, but it shouldn't be related to this issue. It seems I had issue of using Bowtie or GMAP for alignment, may need more time to make it work.
