### ISSUE TITLE
Adding a single track to JBrowse to display variants from multiple samples

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#33]
Back in August, I was investigating whether we could display the exome capture as a single track in JBrowse that showed each SNP call and colour-coded it according to the allele.

I wasn't able to set up the track, but I created this issue to brain dump in case it proves useful in the future:

- The vision: https://github.com/elsiklab/multibigwig
- Need to convert VCF -> BedGraph -> BigWig to use the above plugin
  - BedGraph is like a bed file with a value attached to each genomic "region"
  - Commands to generate: 
    - `bedtools genomecov -i -bga -g`
    - `sort -k1,1 -k1,2n`
  - Then use bedGraphToBigWig
- Limitations:
  - May not be possible to represent hets or more than a single alternate allele.
  - Each sample in a multisample VCF needs its own BigWig file??
- Found this example in the wild: http://gmod.827538.n3.nabble.com/Gmod-ajax-VCF-track-show-single-VCF-as-multiple-tracks-one-per-sample-td4054930.html

**Comment by laceysanderson** [comment]
This is live
