### ISSUE TITLE
Unified PR Template

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#45]
We need a unified PR template for all of our repos to make it easier to provide all the relevant details and to facilitate review :-)

Here is the first draft:

```
<!--- Provide a general summary of your changes in the Title above -->
<!--- No need to include the issue number in the title :-) -->

## Metadata
<!--- If it fixes an open issue, please add the issue link below. -->
 - Issue #

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

## Testing?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, tests ran to see how
      your change affects other areas of the code, etc. -->
<!--- Reviewers will use this section to test the submission! -->
- [ ] I tested on a generic Tripal Site
- [ ] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

## Dependencies
<!-- If this code is dependent upon another module and/or PR, 
       state that here. -->
<!-- Include information about other modules/PRs needed for testing,
        which to enable/merge first, etc. -->
```

And this is what it looks like filled out:
## Metadata

 - Issue #333

- [x] I feel this PR is ready to be merged.
- [x] This PR is dependent upon PR #334

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vestibulum est ac justo egestas, eget hendrerit erat malesuada. Mauris nec sem sem. Suspendisse ac ornare lorem. Aenean lacinia enim a porttitor hendrerit. Nunc vehicula ipsum at felis vestibulum, nec commodo eros convallis. Vestibulum sit amet tellus ut ex rutrum commodo eu quis nunc. Praesent urna velit, venenatis porta imperdiet et, consectetur in diam.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In hac habitasse platea dictumst. Vestibulum ultricies dolor in urna posuere, eget dapibus tortor fermentum. Maecenas arcu eros, facilisis id dui quis, accumsan pretium turpis. Suspendisse lectus sapien, pulvinar sit amet ullamcorper eu, elementum porta elit. Vivamus maximus viverra orci, in porttitor mauris ullamcorper vitae. Donec a viverra mi. Donec vel orci enim. Nulla in sem sit amet mi egestas tempor. Nunc faucibus pretium ex, at pulvinar felis blandit sed. 

## Testing?

- [x] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [x] This PR includes automated testing
1. Enable this
2. Do this thing
3. Clear the cache 3X
4. Go to example page

## Dependencies

This PR is dependent upon moduleX which provides the other-thingy, whereas this module provides updates to the blah blah blah. You need to update moduleX first and enable it before pulling this branch for testing.

**Comment by carolyncaron** [comment]
I think it is a GREAT first draft! :+1:

Perhaps the Dependencies section should be closer to the top, under Metadata? At the very least I think it makes more sense to have it above Testing.

**Comment by laceysanderson** [comment]
Ok, I'll put it above testing. I worry if it's above description, there will be a tendency to describe to much in there. Plus I want context before I jump into the nitty gritty.

```
<!--- Provide a general summary of your changes in the Title above -->
<!--- No need to include the issue number in the title :-) -->

## Metadata
<!--- If it fixes an open issue, please add the issue link below. -->
 - Issue #

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

## Dependencies
<!-- If this code is dependent upon another module and/or PR, 
       state that here. -->
<!-- Include information about other modules/PRs needed for testing,
        which to enable/merge first, etc. -->

## Testing?
<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, tests ran to see how
      your change affects other areas of the code, etc. -->
<!--- Reviewers will use this section to test the submission! -->
- [ ] I tested on a generic Tripal Site
- [ ] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

```

**Comment by laceysanderson** [comment]
Done :-)
