### ISSUE TITLE
Sitewide search sometimes leads to an error page

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#47]
I tried searching for "improve" (I want the stock page for CDC Improve) in the sitewide search bar on the main site and encountered an error. 

Tried some other CDC's and they seem fine... Redberry, Imigreen, Greenstar, Indianhead all return appropriate search results.

Then I tried searching for "lens", and I also get an error. In fact, any search for a genus or species appears to give an error (cicer, pisum, culinaris, vulgaris, etc...)

😱 😱 😱

**Comment by laceysanderson** [comment]
Tried this in the current search and it seems to have fixed itself
