### ISSUE TITLE
Lentil Cross number was duplicated, with 2 KP:GERM numbers 

### ISSUE THREAD

**Issue by ruobinLiu** [UofS-Pulse-Binfo/KnowPulse#52]
1463T    KP:GERM38006    Triple Cross    culinaris
1463T    KP:GERM38007    Triple Cross    culinaris

1915T    KP:GERM38104    Multiple Cross    culinaris
1915T    KP:GERM38105    Multiple Cross    culinaris

1899T    KP:GERM38118    Triple Cross    culinaris
1899T    KP:GERM38119    Triple Cross    culinaris

**Comment by laceysanderson** [comment]
Fixed 👍
