### ISSUE TITLE
KP frontpage has links to questionable pages

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#55]
- Datasets currently links to: http://knowpulse2.usask.ca/portal/search/projects
  - Seems like a bug to me or else this slipped through the cracks since functionality for datasets isn't quite ready... did we intend to link out the listing for projects instead? (http://knowpulse2.usask.ca/portal/research/projects)
  - The same is true for the Datasets link in the sidebar
- JBrowse links to: http://knowpulse2.usask.ca/portal/tools
  - I would expect a listing of the various JBrowses we provide. Instead I'm told it is under development and GBrowse instances also exist 🙃 
  - The same is true for the JBrowse link in the sidebar
- Genotype Comparison Tools links to: http://knowpulse2.usask.ca/portal/search/genotypes/Lens
  - This looks like a generic search box with no helpful text or filters. Perhaps we intended to link here: http://knowpulse2.usask.ca/portal/chado/genotype/Lens
  - If we plan to have matrices for multiple organisms and/or genetic map camparison abilities in the future, a launchpad would be great here

**Comment by laceysanderson** [comment]
> Datasets currently links to: http://knowpulse2.usask.ca/portal/search/projects
>     - Seems like a bug to me or else this slipped through the cracks since functionality for datasets isn't quite ready... did we intend to link out the listing for projects instead? (http://knowpulse2.usask.ca/portal/research/projects)
>     - The same is true for the Datasets link in the sidebar

I hid the Datasets link in the sidebar and changed the one on the frontpage to point to projects.

**Comment by carolyncaron** [comment]
JBrowse links now link to: http://knowpulse2.usask.ca/portal/tools/jbrowse

Genotype Comparison Tools now links to: http://knowpulse2.usask.ca/portal/chado/genotype/Lens
