### ISSUE TITLE
Re-add Germplasm Quick Search to Species pages

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/KnowPulse#56]
Currently having multiple quick searches on a single page causes only the last one to ever be submitted. This caused unintended redirects (e.g. I enter a marker, click search markers and end up on the germplasm search). This needs to be fixed in Tripal Fancy Fields.

**Comment by carolyncaron** [comment]
Marker, project, publication and germplasm quick searches are live on the organism pages, therefore this must be fixed 👍
