### ISSUE TITLE
Some organism pages are stuck in Tripal 2 with questionable content

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#61]
Only the main crops (Common bean, lentil, pea, chickpea and faba bean) have Tripal 3 organism pages. The remainder ([wilds](http://knowpulse.usask.ca/portal/research/wild-species) + [other legumes](http://knowpulse.usask.ca/portal/research/model-species)) are still on Tripal 2.

Additionally, many of these organism pages have questionable content within the "Varieties" and "Sequence and Variant Data" tabs. The Varieties tab for the wild species seems to list the varieties for their genus, not species. For a Sequence Data example, there are supposedly 32,929 + 32,929 contigs for Cowpea in KP which doesn't seem right.

**Comment by laceysanderson** [comment]
Fixed by creating a Tripal 3 species listing here: http://knowpulse.usask.ca/portal/research/species
