### ISSUE TITLE
Non-admin users lack navigation to their account settings

### ISSUE THREAD

**Issue by carolyncaron** [UofS-Pulse-Binfo/KnowPulse#68]
While trying to help a user reset their password (see issue #30), I could not figure out how to direct a non-admin user to their profile page where they can set a new password. (Maybe I just can't find it???)

Fortunately, I was able to provide this user with a direct link, but providing it as a menu item would be ideal. May I suggest it be added to the "Navigation" box in the top right of the page?

**Comment by laceysanderson** [comment]
I added an "Account" link 👍
