### ISSUE TITLE
JBrowse link to Knowpulse on LIS is not wroking

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/KnowPulse#69]
![Screenshot from 2019-04-17 13-16-59](https://user-images.githubusercontent.com/26550071/56316739-51bd9880-6118-11e9-9868-8ace14a3e794.png)

**Comment by Jiu9Shen** [comment]
Above is a screen shot on [LIS genomes page](https://legumeinfo.org/genomes). The link of JBrowse to KnowPulse is not working.

**Comment by Jiu9Shen** [comment]
![Screenshot from 2019-04-17 13-56-24](https://user-images.githubusercontent.com/26550071/56316879-b0831200-6118-11e9-8365-d129bc20cc23.png)

**Comment by laceysanderson** [comment]
Fixed by adding a redirect :-)
