### ISSUE TITLE
A1, A2, A3 were duplicated on Knowpulse

### ISSUE THREAD

**Issue by ruobinLiu** [UofS-Pulse-Binfo/KnowPulse#70]
A1 was duplicated on Knowpulse, with two KP:GERM numbers
A2 was duplicated on Knowpulse, with two KP:GERM numbers
A3 was duplicated on Knowpulse, with two KP:GERM numbers

**Comment by laceysanderson** [comment]
There is no duplication; they were two different genus (Lens & Faba)
